using System;
using System.Collections.Generic;
using System.Globalization;

namespace MitigationFlytext
{
    public static class Localization
    {
        public const string English = "en", Japanese = "ja", Chinese = "zh-CN", Korean = "ko";
        private static readonly Dictionary<string, Dictionary<string, string>> R = new Dictionary<string, Dictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            [English] = Table(
                "PluginTab=Mitigation Flytext|Subtitle=Shows incoming damage, estimated damage before mitigation, and every active mitigation|Settings=Settings|Support=Support|Language=Language|Enabled=Enable overlay|Locked=Lock position and size (click-through)|Preview=Show positioning preview|Duration=Display duration (ms)|Lines=Maximum flytext lines|Opacity=Opacity|FontSize=Text size|Hint=Unlock and enable preview to drag or resize. Gold-framed mitigation icons were applied by you.|PreviewText=POSITION PREVIEW  48,120 [60,000] (-19.8%)|PreviewDetail=RP  KE  Your mitigation is highlighted in gold|SupportHeading=Support Roxyz0501's development|SupportBody=Support is completely optional. Every feature remains available with no differences if you do not support.|SupportButton=Support Roxyz0501 on Ko-fi|LinkFailed=Could not open the link: {0}|Started=Mitigation Flytext: Started|Stopped=Mitigation Flytext: Stopped|SaveError=Could not save settings: {0}|EstimateNote=Before-mitigation values are estimates calculated from the tracked percentage mitigations. Shields, block/parry, damage-type-specific effects, and unlisted statuses can cause differences.|Updates=Updates|CheckStartup=Check for updates when the plugin starts|CheckNow=Check now|Checking=Checking for updates…|UpToDate=Latest version installed ({0}).|NoRelease=No stable release was found.|CheckFailed=Update check failed; normal operation continues.|UpdateAvailable=Update available: {0} → {1}\r\n{2}|UpdateNow=Update|Later=Later|Preparing=Downloading and verifying…|Prepared=Prepared. Exit ACT, then restart it to finish.|UpdateFailed=Update failed safely: {0}"),
            [Japanese] = Table(
                "PluginTab=被ダメージフライテキスト|Subtitle=受けたダメージ・軽減前推定値・入っていた軽減を表示します|Settings=設定|Support=支援|Language=言語|Enabled=オーバーレイを有効にする|Locked=位置とサイズを固定（クリック透過）|Preview=位置調整プレビューを表示|Duration=表示時間（ミリ秒）|Lines=最大表示行数|Opacity=透明度|FontSize=文字サイズ|Hint=固定をOFF、プレビューをONにして移動・サイズ変更できます。自分が入れた軽減は金色の枠で強調されます。|PreviewText=位置プレビュー  48,120 [60,000] (-19.8%)|PreviewDetail=RP  KE  金枠は自分が入れた軽減|SupportHeading=Roxyz0501の開発を支援|SupportBody=支援は完全に任意です。支援しなくてもすべての機能を利用でき、機能差はありません。|SupportButton=Ko-fiでRoxyz0501を支援する|LinkFailed=リンクを開けませんでした: {0}|Started=Mitigation Flytext: 起動済み|Stopped=Mitigation Flytext: 停止|SaveError=設定を保存できませんでした: {0}|EstimateNote=軽減前ダメージは、追跡できた割合軽減から算出する推定値です。バリア、ブロック／受け流し、ダメージ属性限定効果、未登録ステータスにより差が出ることがあります。|Updates=更新|CheckStartup=起動時に更新を確認する|CheckNow=今すぐ確認|Checking=更新を確認しています…|UpToDate=最新版です（{0}）。|NoRelease=安定版Releaseがありません。|CheckFailed=更新確認に失敗しました。通常機能は継続します。|UpdateAvailable=更新があります: {0} → {1}\r\n{2}|UpdateNow=更新する|Later=後で|Preparing=ダウンロードして検証しています…|Prepared=準備完了。ACTを終了し、再起動すると更新されます。|UpdateFailed=更新を安全に中止しました: {0}"),
            [Chinese] = Table(
                "PluginTab=承伤浮动文字|Subtitle=显示承受伤害、减伤前估算值以及全部生效减伤|Settings=设置|Support=支持|Language=语言|Enabled=启用悬浮窗|Locked=锁定位置和大小（鼠标穿透）|Preview=显示位置预览|Duration=显示时间（毫秒）|Lines=最大显示行数|Opacity=透明度|FontSize=文字大小|Hint=解除锁定并开启预览后可拖动或缩放。由您施加的减伤会以金色边框突出显示。|PreviewText=位置预览  48,120 [60,000] (-19.8%)|PreviewDetail=RP  KE  金框表示您施加的减伤|SupportHeading=支持Roxyz0501的开发|SupportBody=支持完全自愿。即使不支持，也可以使用全部功能，不存在功能差异。|SupportButton=在Ko-fi上支持Roxyz0501|LinkFailed=无法打开链接: {0}|Started=Mitigation Flytext: 已启动|Stopped=Mitigation Flytext: 已停止|SaveError=无法保存设置: {0}|EstimateNote=减伤前伤害根据已追踪的百分比减伤估算。护盾、格挡／招架、限定伤害类型效果及未登记状态可能造成误差。|Updates=更新|CheckStartup=插件启动时检查更新|CheckNow=立即检查|Checking=正在检查更新…|UpToDate=当前已是最新版（{0}）。|NoRelease=未找到稳定版Release。|CheckFailed=检查更新失败，插件会继续正常运行。|UpdateAvailable=发现更新: {0} → {1}\r\n{2}|UpdateNow=更新|Later=稍后|Preparing=正在下载并验证…|Prepared=准备完成。退出并重启ACT后完成更新。|UpdateFailed=已安全停止更新: {0}"),
            [Korean] = Table(
                "PluginTab=받은 피해 플라이텍스트|Subtitle=받은 피해, 경감 전 추정치와 적용된 모든 경감을 표시합니다|Settings=설정|Support=후원|Language=언어|Enabled=오버레이 사용|Locked=위치와 크기 잠금(클릭 통과)|Preview=위치 미리보기 표시|Duration=표시 시간(ms)|Lines=최대 표시 줄 수|Opacity=투명도|FontSize=글자 크기|Hint=잠금을 해제하고 미리보기를 켜면 이동하거나 크기를 바꿀 수 있습니다. 내가 적용한 경감은 금색 테두리로 강조됩니다.|PreviewText=위치 미리보기  48,120 [60,000] (-19.8%)|PreviewDetail=RP  KE  금색 테두리는 내가 적용한 경감|SupportHeading=Roxyz0501의 개발 후원|SupportBody=후원은 완전히 선택 사항입니다. 후원하지 않아도 모든 기능을 차이 없이 사용할 수 있습니다.|SupportButton=Ko-fi에서 Roxyz0501 후원하기|LinkFailed=링크를 열 수 없습니다: {0}|Started=Mitigation Flytext: 시작됨|Stopped=Mitigation Flytext: 중지됨|SaveError=설정을 저장할 수 없습니다: {0}|EstimateNote=경감 전 피해는 추적된 비율 경감으로 계산한 추정치입니다. 보호막, 방어／받아넘기기, 피해 속성 한정 효과와 미등록 상태로 오차가 생길 수 있습니다.|Updates=업데이트|CheckStartup=플러그인 시작 시 업데이트 확인|CheckNow=지금 확인|Checking=업데이트 확인 중…|UpToDate=최신 버전입니다({0}).|NoRelease=안정 버전 Release가 없습니다.|CheckFailed=업데이트 확인에 실패했습니다. 일반 기능은 계속됩니다.|UpdateAvailable=업데이트 있음: {0} → {1}\r\n{2}|UpdateNow=업데이트|Later=나중에|Preparing=다운로드 및 검증 중…|Prepared=준비 완료. ACT를 종료하고 다시 시작하면 업데이트됩니다.|UpdateFailed=업데이트를 안전하게 중단했습니다: {0}")
        };
        private static Dictionary<string, string> Table(string packed) { var d = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase); foreach (var p in packed.Split('|')) { var n = p.IndexOf('='); d[p.Substring(0, n)] = p.Substring(n + 1); } return d; }
        public static string NormalizeLanguage(string value) { if (string.IsNullOrWhiteSpace(value)) return English; if (value.StartsWith("ja", StringComparison.OrdinalIgnoreCase)) return Japanese; if (value.StartsWith("zh", StringComparison.OrdinalIgnoreCase)) return Chinese; if (value.StartsWith("ko", StringComparison.OrdinalIgnoreCase)) return Korean; return English; }
        public static string MapCulture(CultureInfo value) => NormalizeLanguage(value == null ? null : value.Name);
        public static string FontFamily(string value) { switch (NormalizeLanguage(value)) { case Japanese: return "Yu Gothic UI"; case Chinese: return "Microsoft YaHei UI"; case Korean: return "Malgun Gothic"; default: return "Segoe UI"; } }
        public static string Get(string language, string key, params object[] args) { string value; Dictionary<string, string> t; if (!R.TryGetValue(NormalizeLanguage(language), out t) || !t.TryGetValue(key, out value)) R[English].TryGetValue(key, out value); value = value ?? key; return args == null || args.Length == 0 ? value : string.Format(CultureInfo.CurrentCulture, value, args); }
    }
}
