<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>MitigationFlytext.Updater</AssemblyName>
    <RootNamespace>MitigationFlytext.Updater</RootNamespace>
    <Version>1.0.2</Version>
    <Authors>Roxyz0501</Authors>
    <Company>Roxyz0501</Company>
    <Product>Mitigation Flytext Updater</Product>
    <Copyright>Copyright © Roxyz0501</Copyright>
  </PropertyGroup>
</Project>
